name: file-analyser
on:
  schedule:
    - cron: '00 14 * * *'
  workflow_dispatch:

jobs:
  file-matcher:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - run: | 
           pwd
           ls -la
    - uses: saurabh0jha/github-actions-poc@master
      with: 
        folderPath: 'levels/nested-level'
